baseURL = 'https://aj-0-1.github.io/blog/'
languageCode = 'en-us'
title = 'aj-0-1'
theme = 'terminal'

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2

[[menu.main]]
  identifier = "notes"
  name = "Notes"
  pageRef = "/notes"
  weight = 1
