baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'aj-0-1'
theme = 'terminal'

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2

[[menu.main]]
  identifier = "notes"
  name = "Notes"
  url = "/notes/"
  weight = 1
